import { Link, Navigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { SEO, structuredData } from "@/components/SEO";
import {
  AlertTriangle,
  CalendarDays,
  CheckCircle2,
  ChevronRight,
  RefreshCw,
  Sparkles,
} from "lucide-react";

const features = [
  {
    title: "Two-Way Sync Mocking",
    description: "Test how your PMS handles external updates, conflicts, and edge cases.",
    icon: RefreshCw,
  },
  {
    title: "RFC 5545 Compliant Feeds",
    description: "Generate strict iCalendar output that mirrors real partner behavior.",
    icon: CalendarDays,
  },
  {
    title: "Conflict Detection",
    description: "Surface overlaps and duplicates instantly across multiple calendars.",
    icon: AlertTriangle,
  },
];

const steps = [
  {
    title: "Create a mock calendar",
    description: "Spin up multiple partner feeds in seconds without backend wiring.",
  },
  {
    title: "Subscribe your app",
    description: "Use the public feed URL to test inbound and outbound sync flows.",
  },
  {
    title: "Validate edge cases",
    description: "Trigger overlaps, cancellations, and conflicts to harden logic.",
  },
];

export default function LandingPage() {
  const { user, loading } = useAuth();

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background text-foreground">
        <div className="flex items-center gap-3 text-sm text-muted-foreground">
          <Sparkles className="h-4 w-4" />
          Loading iCal Tester...
        </div>
      </div>
    );
  }

  if (user) {
    return <Navigate to="/dashboard" replace />;
  }

  // Combined structured data for homepage
  const homeStructuredData = {
    "@context": "https://schema.org",
    "@graph": [
      structuredData.organization(),
      structuredData.softwareApplication(),
      structuredData.faqPage([
        {
          question: "What is iCal Tester Pro?",
          answer: "iCal Tester Pro is a professional mock server for testing iCal/ICS calendar synchronization. It helps developers debug integrations with Booking.com, Airbnb, VRBO, and other OTA platforms.",
        },
        {
          question: "Is iCal Tester Pro free to use?",
          answer: "Yes, iCal Tester Pro offers a free tier that includes core features for testing calendar sync. Premium features are available for professional teams.",
        },
        {
          question: "Does it support RFC 5545 iCalendar format?",
          answer: "Yes, all feeds generated by iCal Tester Pro are fully RFC 5545 compliant, ensuring compatibility with all major calendar and booking platforms.",
        },
      ]),
    ],
  };

  return (
    <>
      <SEO
        canonical="/"
        structuredData={homeStructuredData}
      />
      <div className="relative min-h-screen bg-background text-foreground overflow-hidden">
        <div className="absolute -top-40 right-0 h-96 w-96 rounded-full bg-brand-gradient opacity-20 blur-3xl" />
        <div className="absolute bottom-0 left-0 h-80 w-80 rounded-full bg-brand-gradient opacity-15 blur-3xl" />

      <nav className="fixed top-0 z-50 w-full border-b border-border glass-surface">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2 text-lg font-bold">
            <CalendarDays className="h-5 w-5 text-primary" />
            iCal Tester Pro
          </Link>
          <div className="hidden items-center gap-8 text-sm font-medium text-muted-foreground md:flex">
            <a href="#features" className="transition-colors hover:text-primary">
              Features
            </a>
            <a href="#how-it-works" className="transition-colors hover:text-primary">
              How it works
            </a>
            <Button asChild className="rounded-full px-5">
              <Link to="/auth">Start Free</Link>
            </Button>
          </div>
        </div>
      </nav>

      <main className="relative pt-28">
        <section className="px-4 pb-20">
          <div className="mx-auto max-w-6xl text-center">
            <div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-muted px-4 py-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              <span className="h-2 w-2 rounded-full bg-primary" />
              Version 2.0 Now Live
            </div>
            <h1 className="text-hero-lg font-extrabold">
              Test iCal integrations
              <span className="block text-brand-gradient">with total confidence</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-base text-muted-foreground md:text-lg">
              The professional developer suite for mocking, debugging, and validating calendar sync.
              Built for PMS teams and booking platform engineers.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button asChild size="lg" className="rounded-full px-8 shadow-brand">
                <Link to="/auth">Launch Dashboard Free</Link>
              </Button>
              <a
                href="https://example.com/docs"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-2 rounded-full border border-border px-6 py-3 text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground"
              >
                View Docs
                <ChevronRight className="h-4 w-4" />
              </a>
            </div>

            <div className="relative mt-14">
              <div className="absolute inset-0 -z-10 rounded-3xl bg-brand-gradient opacity-20 blur-3xl" />
              <img
                src="/IcalTester.png"
                alt="iCal Tester dashboard preview"
                className="mx-auto w-full max-w-5xl rounded-3xl border border-border bg-card p-6 shadow-2xl"
              />
            </div>
          </div>
        </section>

        <section id="features" className="border-y border-border bg-muted/30 px-4 py-20">
          <div className="mx-auto max-w-6xl">
            <div className="mb-12 text-center">
              <h2 className="text-hero font-bold">Everything you need to mock calendars</h2>
              <p className="mt-4 text-muted-foreground">
                Skip complex backends. Spin up mock feeds, test edge cases, and ship with confidence.
              </p>
            </div>
            <div className="grid gap-6 md:grid-cols-3">
              {features.map((feature) => {
                const Icon = feature.icon;
                return (
                  <div
                    key={feature.title}
                    className="rounded-3xl border border-border bg-card p-6 shadow-sm transition-transform hover:-translate-y-1 hover:shadow-xl"
                  >
                    <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                      <Icon className="h-5 w-5" />
                    </div>
                    <h3 className="text-lg font-semibold">{feature.title}</h3>
                    <p className="mt-2 text-sm text-muted-foreground">{feature.description}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        <section id="how-it-works" className="px-4 py-20">
          <div className="mx-auto max-w-6xl">
            <div className="mb-10 flex items-center justify-between">
              <div>
                <h2 className="text-hero font-bold">How it works</h2>
                <p className="mt-3 text-muted-foreground">
                  A simple workflow that matches how PMS teams test live integrations.
                </p>
              </div>
              <div className="hidden items-center gap-2 rounded-full bg-muted px-4 py-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground md:flex">
                <CheckCircle2 className="h-4 w-4 text-primary" />
                Zero backend setup
              </div>
            </div>
            <div className="grid gap-6 md:grid-cols-3">
              {steps.map((step, index) => (
                <div key={step.title} className="rounded-3xl border border-border bg-card p-6">
                  <div className="mb-4 text-xs font-semibold uppercase tracking-widest text-primary">
                    Step {index + 1}
                  </div>
                  <h3 className="text-lg font-semibold">{step.title}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 pb-16">
          <div className="mx-auto max-w-6xl rounded-3xl border border-border bg-card p-8 text-center shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-muted-foreground">
              Trusted by developers at
            </p>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-8 text-lg font-semibold text-muted-foreground">
              <span>AirStay</span>
              <span>BookMyVilla</span>
              <span>PropTech Lab</span>
              <span>SyncroCal</span>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-border bg-muted/40 px-4 py-16">
        <div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-4">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 text-xl font-bold">
              <CalendarDays className="h-5 w-5 text-primary" />
              iCal Tester Pro
            </div>
            <p className="mt-4 max-w-sm text-sm text-muted-foreground">
              The professional environment for calendar developers. Built by engineers, for engineers.
            </p>
          </div>
          <div>
            <h4 className="text-sm font-semibold">Product</h4>
            <ul className="mt-4 space-y-3 text-sm text-muted-foreground">
              <li>
                <a href="#" className="hover:text-foreground">
                  Documentation
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-foreground">
                  API Reference
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-foreground">
                  Changelog
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h4 className="text-sm font-semibold">Company</h4>
            <ul className="mt-4 space-y-3 text-sm text-muted-foreground">
              <li>
                <Link to="/privacy" className="hover:text-foreground">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <a href="#" className="hover:text-foreground">
                  Terms of Service
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-foreground">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div className="mx-auto mt-10 max-w-6xl border-t border-border pt-6 text-center text-xs text-muted-foreground">
          (c) 2025 iCal Tester Pro. All rights reserved.
        </div>
        </footer>
      </div>
    </>
  );
}
