#!/usr/bin/env node
/**
 * One-command local start: Supabase (Docker) + migrations + .env + dev server.
 * Cross-platform (Node 18+). Use: npm run local
 */
import { spawn } from "child_process";
import { writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, {
      stdio: "inherit",
      shell: true,
      cwd: projectRoot,
      ...opts,
    });
    p.on("exit", (code) => (code === 0 ? resolve() : reject(new Error(`Exit ${code}`))));
  });
}

function runCapture(cmd, args) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, {
      stdio: ["ignore", "pipe", "pipe"],
      shell: true,
      cwd: projectRoot,
    });
    let out = "";
    let err = "";
    p.stdout?.on("data", (d) => (out += d.toString()));
    p.stderr?.on("data", (d) => (err += d.toString()));
    p.on("exit", (code) => {
      if (code !== 0) reject(new Error(err || out || `Exit ${code}`));
      else resolve(out.trim());
    });
  });
}

async function main() {
  console.log("\niCal Tester – local start (Supabase + app)\n");

  console.log("[1/4] Starting Supabase (Docker)...");
  await run("npx", ["supabase", "start"]);

  console.log("[2/4] Applying migrations (supabase db reset)...");
  try {
    await run("npx", ["supabase", "db", "reset", "--no-seed"]);
  } catch (e) {
    console.warn("  supabase db reset failed (e.g. 502 on container restart). Supabase may already be up; continuing.");
  }

  console.log("[3/4] Writing .env from Supabase status...");
  let statusJson;
  try {
    statusJson = await runCapture("npx", ["supabase", "status", "-o", "json"]);
  } catch (e) {
    console.error("Could not get supabase status. Run 'npx supabase status' and set .env manually.");
    process.exit(1);
  }
  const status = JSON.parse(statusJson);
  const apiUrl = status.api_url || status.API_URL;
  const publishableKey =
    status.publishable_key ?? status.Publishable ?? status.anon_key ?? status.ANON_KEY;
  if (!apiUrl || !publishableKey) {
    console.error("Missing api_url or publishable/anon key in status. Set .env manually.");
    process.exit(1);
  }
  const envContent = `# Generated by scripts/local-up.mjs – local Supabase
VITE_SUPABASE_URL=${apiUrl}
VITE_SUPABASE_PUBLISHABLE_KEY=${publishableKey}
VITE_SUPABASE_FUNCTIONS_URL=${apiUrl}
VITE_PUBLIC_FEED_BASE_URL=http://localhost:5173
ICS_CRON_SECRET=local-dev-secret
`;
  await writeFile(path.join(projectRoot, ".env"), envContent, "utf8");
  console.log("  -> .env updated (API URL: " + apiUrl + ")");

  console.log("[4/4] Installing dependencies and starting dev server...");
  await run("npm", ["install", "--no-audit", "--no-fund"]);
  console.log("\nDev server at http://localhost:5173");
  console.log("For public ICS feed, run in another terminal: npx supabase functions serve\n");
  await run("npm", ["run", "dev"]);
}

main().catch((e) => {
  console.error(e.message || e);
  process.exit(1);
});
