# One-command local start: Supabase (Docker) + migrations + .env + dev server
# Requires: Docker running, Node.js, Supabase CLI (npx supabase is fine)
# Usage: .\scripts\local-up.ps1  or  npm run local

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not (Test-Path "$ProjectRoot\package.json")) {
    $ProjectRoot = (Get-Location).Path
}
Set-Location $ProjectRoot

Write-Host "iCal Tester – local start (Supabase + app)" -ForegroundColor Cyan
Write-Host ""

# 1) Supabase: start (idempotent if already running)
Write-Host "[1/4] Starting Supabase (Docker)..." -ForegroundColor Yellow
& npx supabase start 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "Supabase start failed. Is Docker running?" -ForegroundColor Red
    exit 1
}

# 2) Apply migrations
Write-Host "[2/4] Applying migrations (supabase db reset)..." -ForegroundColor Yellow
& npx supabase db reset --no-seed 2>&1 | Out-Host
if ($LASTEXITCODE -ne 0) {
    Write-Host "supabase db reset failed." -ForegroundColor Red
    exit 1
}

# 3) Write .env from supabase status
Write-Host "[3/4] Writing .env from Supabase status..." -ForegroundColor Yellow
$statusJson = & npx supabase status -o json 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "supabase status failed: $statusJson" -ForegroundColor Red
    exit 1
}
$status = $statusJson | ConvertFrom-Json
$apiUrl = if ($status.api_url) { $status.api_url } else { $status.API_URL }
$anonKey = if ($status.anon_key) { $status.anon_key } else { $status.ANON_KEY }
if (-not $apiUrl -or -not $anonKey) {
    Write-Host "Could not read API URL or anon key from supabase status." -ForegroundColor Red
    exit 1
}

$envContent = @"
# Generated by scripts/local-up.ps1 – local Supabase
VITE_SUPABASE_URL=$apiUrl
VITE_SUPABASE_PUBLISHABLE_KEY=$anonKey
VITE_SUPABASE_FUNCTIONS_URL=$apiUrl
VITE_PUBLIC_FEED_BASE_URL=http://localhost:5173
ICS_CRON_SECRET=local-dev-secret
"@
$envContent | Set-Content -Path "$ProjectRoot\.env" -Encoding utf8
Write-Host "  -> .env updated (API URL: $apiUrl)" -ForegroundColor Green

# 4) Install deps and run dev server
Write-Host "[4/4] Installing dependencies and starting dev server..." -ForegroundColor Yellow
if (-not (Test-Path "$ProjectRoot\node_modules")) {
    & npm ci --no-audit --no-fund 2>&1 | Out-Host
    if ($LASTEXITCODE -ne 0) { & npm install --no-audit --no-fund 2>&1 | Out-Host }
} else {
    & npm install --no-audit --no-fund 2>&1 | Out-Null
}
Write-Host ""
Write-Host "Dev server starting at http://localhost:5173" -ForegroundColor Green
Write-Host "For public ICS feed, run in another terminal: npx supabase functions serve" -ForegroundColor Gray
Write-Host ""
& npm run dev
