#!/usr/bin/env bash
# One-command local start: Supabase (Docker) + migrations + .env + dev server
# Requires: Docker running, Node.js, Supabase CLI (npx supabase is fine)
# Usage: ./scripts/local-up.sh  or  npm run local

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo ""
echo "iCal Tester – local start (Supabase + app)"
echo ""

# 1) Supabase: start (idempotent if already running)
echo "[1/4] Starting Supabase (Docker)..."
npx supabase start

# 2) Apply migrations
echo "[2/4] Applying migrations (supabase db reset)..."
npx supabase db reset --no-seed

# 3) Write .env from supabase status
echo "[3/4] Writing .env from Supabase status..."
if command -v jq &>/dev/null; then
  STATUS_JSON="$(npx supabase status -o json)"
  API_URL="$(echo "$STATUS_JSON" | jq -r '.api_url // .API_URL // empty')"
  ANON_KEY="$(echo "$STATUS_JSON" | jq -r '.anon_key // .ANON_KEY // empty')"
else
  # Fallback: parse pretty output (best-effort)
  API_URL="$(npx supabase status 2>/dev/null | grep -E 'API URL|api url' -i | head -1 | sed -E 's/.*(http[s]?:\/\/[^ ]+).*/\1/' || true)"
  ANON_KEY=""
  if [ -z "$API_URL" ]; then
    echo "Could not get API URL. Install jq or copy from 'npx supabase status' into .env"
    exit 1
  fi
  echo "  Install 'jq' for automatic .env. For now set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env manually."
fi

if [ -n "$API_URL" ] && [ -n "$ANON_KEY" ]; then
  cat > .env << EOF
# Generated by scripts/local-up.sh – local Supabase
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
VITE_SUPABASE_FUNCTIONS_URL=$API_URL
VITE_PUBLIC_FEED_BASE_URL=http://localhost:5173
ICS_CRON_SECRET=local-dev-secret
EOF
  echo "  -> .env updated (API URL: $API_URL)"
else
  echo "  Could not read api_url or anon_key. Set .env manually from: npx supabase status"
  exit 1
fi

# 4) Install deps and run dev server
echo "[4/4] Installing dependencies and starting dev server..."
[ -d node_modules ] || npm ci --no-audit --no-fund 2>/dev/null || npm install --no-audit --no-fund
echo ""
echo "Dev server starting at http://localhost:5173"
echo "For public ICS feed, run in another terminal: npx supabase functions serve"
echo ""
exec npm run dev
